---
---
include:
  # -------------------------------
  # Left half
  # -------------------------------
  - board: eyelash_corne_left
    shield: nice_view      # optional OLED/display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_corne_studio_left

  # -------------------------------
  # Right half
  # -------------------------------
  - board: eyelash_corne_right
    shield: nice_view      # optional OLED/display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_corne_studio_right

  # -------------------------------
  # Dongle
  # -------------------------------
  - board: eyelash_corne_dongle
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: eyelash_corne_dongle


 
