include:
  # -------------------------------
  # Left half (peripheral)
  # -------------------------------
  - board: eyelash_corne_left
    shield: nice_view
    artifact-name: eyelash_corne_left

  # -------------------------------
  # Right half (peripheral)
  # -------------------------------
  - board: eyelash_corne_right
    shield: nice_view
    artifact-name: eyelash_corne_right

  # -------------------------------
  # Dongle (central + USB + Studio)
  # -------------------------------
  - board: eyelash_corne_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_corne_dongle


 
